### ISSUE TITLE
看规约文档上是7E7EH，为何代码这里的变量定义的是7E7E呢？

### ISSUE THREAD

**Issue by liugt34** [handsomestWei/sl651-2014#3]
看规约文档上是7E7EH，为何代码这里的变量定义的是7E7E呢？
![image](https://user-images.githubusercontent.com/8056013/198960125-582d5b5e-4571-45d1-b474-0202e6d31028.png)

![image](https://user-images.githubusercontent.com/8056013/198960184-aecfc7a7-8c1b-40c6-8700-5de82c9685c4.png)

**Comment by handsomestWei** [comment]
这里的H是指hex十六进制字符串的意思，来说明报文内容7E7E不是普通的字符串

**Comment by liugt34** [comment]
谢谢
